### PR TITLE
Open up friendly_id in the gemspec

### PR DESCRIPTION
**Pull request by aouji**

### CODE REVIEW

**Comment by aouji** [comment]
Should only be merged after fme cloud production stack is updated to rails 4

**Comment by pouellet** [comment]
As far as I know, the github gems are locked on a revision, so this should not be an issue.

**Comment by pouellet** [comment]
:+1:

**Comment by aouji** [comment]
Something like bundle update will break this for production. But yes, bundle update will break a lot of things!

**Pull request merged**
